"""Re-naming address

Revision ID: d697e6091ad5
Revises: c3cb347bf20b
Create Date: 2024-06-26 15:43:04.731894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd697e6091ad5'
down_revision = 'c3cb347bf20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',new_column_name='location')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',new_column_name='address')
    
    # ### end Alembic commands ###
